Fixed update failure recovery and dnsmasq selection

diff --git a/ruantiblock/files/usr/bin/ruantiblock b/ruantiblock/files/usr/bin/ruantiblock
--- a/ruantiblock/files/usr/bin/ruantiblock
+++ b/ruantiblock/files/usr/bin/ruantiblock
@@ -449,10 +449,12 @@ RestartDnsmasq() {
 
 MergeDnsmasqNftsets() {
     local _return_code=0
-    local _bypass_tmp="${DNSMASQ_CONFIG_FILE_BYPASS}.tmp"
-    local _user_tmp="${DNSMASQ_CONFIG_FILE_USER_INSTANCES}.tmp"
-    local _main_tmp="${DNSMASQ_CONFIG_FILE}.tmp"
-    local _merged_tmp="${DNSMASQ_DATA_FILE_NFTSETS}.tmp"
+    local _stage _target _index=0
+    _stage=$(mktemp -d "${DATA_DIR}/dns-publish.XXXXXX") || return 1
+    local _bypass_tmp="${_stage}/bypass"
+    local _user_tmp="${_stage}/users"
+    local _main_tmp="${_stage}/main"
+    local _merged_tmp="${_stage}/merged"
 
     $AWK_CMD '$0 !~ /^nftset=\//' "$DNSMASQ_DATA_FILE_BYPASS" > "$_bypass_tmp" || _return_code=1
     $AWK_CMD '$0 !~ /^nftset=\//' "$DNSMASQ_DATA_FILE_USER_INSTANCES" > "$_user_tmp" || _return_code=1
@@ -518,10 +520,29 @@ MergeDnsmasqNftsets() {
     fi
 
     if [ $_return_code -eq 0 ]; then
-        mv -f "$_bypass_tmp" "$DNSMASQ_CONFIG_FILE_BYPASS" || _return_code=1
-        mv -f "$_user_tmp" "$DNSMASQ_CONFIG_FILE_USER_INSTANCES" || _return_code=1
-        mv -f "$_main_tmp" "$DNSMASQ_CONFIG_FILE" || _return_code=1
-        mv -f "$_merged_tmp" "$DNSMASQ_DATA_FILE_NFTSETS" || _return_code=1
+        for _target in "$DNSMASQ_CONFIG_FILE_BYPASS" "$DNSMASQ_CONFIG_FILE_USER_INSTANCES" "$DNSMASQ_CONFIG_FILE" "$DNSMASQ_DATA_FILE_NFTSETS"; do
+            _index=$((_index + 1))
+            if [ -e "$_target" ]; then
+                cp -p "$_target" "${_stage}/old.${_index}" || _return_code=1
+            fi
+        done
+    fi
+    if [ $_return_code -eq 0 ]; then
+        if ! { mv -f "$_bypass_tmp" "$DNSMASQ_CONFIG_FILE_BYPASS" &&
+               mv -f "$_user_tmp" "$DNSMASQ_CONFIG_FILE_USER_INSTANCES" &&
+               mv -f "$_main_tmp" "$DNSMASQ_CONFIG_FILE" &&
+               mv -f "$_merged_tmp" "$DNSMASQ_DATA_FILE_NFTSETS"; }; then
+            _return_code=1
+            _index=0
+            for _target in "$DNSMASQ_CONFIG_FILE_BYPASS" "$DNSMASQ_CONFIG_FILE_USER_INSTANCES" "$DNSMASQ_CONFIG_FILE" "$DNSMASQ_DATA_FILE_NFTSETS"; do
+                _index=$((_index + 1))
+                if [ -e "${_stage}/old.${_index}" ]; then
+                    cp -p "${_stage}/old.${_index}" "$_target" || MakeLogRecord "err" "DNS rollback failed: ${_target}"
+                else
+                    rm -f "$_target"
+                fi
+            done
+        fi
     fi
 
     if [ $_return_code -ne 0 ]; then
@@ -529,6 +550,7 @@ MergeDnsmasqNftsets() {
         echo " Error! Unable to merge dnsmasq nftset rules" >&2
         MakeLogRecord "err" "Error! Unable to merge dnsmasq nftset rules"
     fi
+    rm -rf "$_stage"
     return $_return_code
 }
 
@@ -944,11 +966,11 @@ ClearDataFiles() {
     if [ -d "$DNSMASQ_CONFDIR" ]; then
          if [ -z "$_arg" -o "$_arg" = "main_instance" ]; then
             printf "" > "$DNSMASQ_DATA_FILE"
-            printf "" > "$DNSMASQ_CONFIG_FILE"
+            [ -n "$_arg" ] || printf "" > "$DNSMASQ_CONFIG_FILE"
         fi
         if [ -z "$_arg" -o "$_arg" = "user_instances" ]; then
             printf "" > "$DNSMASQ_DATA_FILE_USER_INSTANCES"
-            printf "" > "$DNSMASQ_CONFIG_FILE_USER_INSTANCES"
+            [ -n "$_arg" ] || printf "" > "$DNSMASQ_CONFIG_FILE_USER_INSTANCES"
         fi
         if [ -z "$_arg" ]; then
             printf "" > "$DNSMASQ_DATA_FILE_BYPASS"
@@ -979,19 +1001,30 @@ AddBypassEntries() {
         printf "" > "$IP_DATA_FILE_BYPASS"
         printf "flush set %s %s\nflush set %s %s\n" "$NFT_TABLE" "$NFTSET_BYPASS_IP" "$NFT_TABLE" "$NFTSET_BYPASS_FQDN" >> "$IP_DATA_FILE_BYPASS"
     fi
-    FlushNftSets "$NFTSET_BYPASS_IP" "$NFTSET_BYPASS_FQDN"
     if [ "$BYPASS_MODE" = "1" ]; then
         if [ -f "$BYPASS_ENTRIES_FILE" ]; then
             $AWK_CMD '
                 BEGIN {
                     delete ip_array;
                     delete fqdn_array;
+                    default_dns = ENVIRON["BYPASS_ENTRIES_DNS"];
+                    if(length(default_dns)) {
+                        split(default_dns, default_parts, "#");
+                        if(!validIP(default_parts[1]) || (length(default_parts[2]) && (default_parts[2] !~ /^[0-9]+$/ || default_parts[2] + 0 > 65535))) failed = 1;
+                    };
                 }
                 function writeIpList(array,  _str) {
                     for(i in array) {
                         _str = _str i ",";
                     };
                     return _str;
+                };
+                function validIP(value,  count, octets, k) {
+                    count = split(value, octets, ".");
+                    if(count != 4) return 0;
+                    for(k = 1; k <= 4; k++)
+                        if(octets[k] !~ /^[0-9]+$/ || octets[k] + 0 > 255) return 0;
+                    return 1;
                 };
                 function writeDNSData(val, dns) {
                     if(length(dns) == 0 && length(ENVIRON["BYPASS_ENTRIES_DNS"]) > 0) {
@@ -1011,13 +1044,21 @@ AddBypassEntries() {
                 ($0 !~ /^([\040\011]*$|#)/) {
                     sub("\015", "", $0);
                     if($0 ~ /^[0-9]{1,3}([.][0-9]{1,3}){3}([\057][0-9]{1,2})?$/) {
+                        split($0, cidr, "/");
+                        if(!validIP(cidr[1]) || (length(cidr[2]) && cidr[2] + 0 > 32)) { failed = 1; next; };
                         ip_array[$0];
                     }
                     else if($0 ~ /^([a-z0-9._-]+[.])*([a-z]{2,}|xn--[a-z0-9]+)([ ][0-9]{1,3}([.][0-9]{1,3}){3}([#][0-9]{2,5})?)?$/) {
+                        split($0, entry, " ");
+                        if(length(entry[2])) {
+                            split(entry[2], dns, "#");
+                            if(!validIP(dns[1]) || (length(dns[2]) && dns[2] + 0 > 65535)) { failed = 1; next; };
+                        };
                         fqdn_array[$0];
                     };
                 }
                 END {
+                    if(failed) exit 1;
                     printf "table %s {\n%s", ENVIRON["NFT_TABLE"], ENVIRON["NFTSET_BYPASS_IP_STRING"] >> ENVIRON["IP_DATA_FILE_BYPASS"];
                     if(length(ip_array) > 0) {
                         printf "elements={%s};", writeIpList(ip_array) >> ENVIRON["IP_DATA_FILE_BYPASS"];
@@ -1232,9 +1273,37 @@ GetMainInstanceEntries() {
 }
 
 GetBlacklistFiles() {
+    local _snapshot _file _index=0 _result
+    PreStartCheck
+    _snapshot=$(mktemp -d "${DATA_DIR}/prepare.XXXXXX") || return 4
+    for _file in "$DNSMASQ_DATA_FILE" "$DNSMASQ_DATA_FILE_BYPASS" "$DNSMASQ_DATA_FILE_USER_INSTANCES" "$IP_DATA_FILE" "$IP_DATA_FILE_BYPASS" "$IP_DATA_FILE_USER_INSTANCES" "$UPDATE_STATUS_FILE" "$USER_ENTRIES_STATUS_FILE"; do
+        _index=$((_index + 1))
+        if [ -f "$_file" ]; then
+            cp -p "$_file" "${_snapshot}/${_index}" || { rm -rf "$_snapshot"; return 4; }
+        fi
+    done
+    PrepareBlacklistFiles
+    _result=$?
+    if [ $_result -eq 4 ]; then
+        _index=0
+        for _file in "$DNSMASQ_DATA_FILE" "$DNSMASQ_DATA_FILE_BYPASS" "$DNSMASQ_DATA_FILE_USER_INSTANCES" "$IP_DATA_FILE" "$IP_DATA_FILE_BYPASS" "$IP_DATA_FILE_USER_INSTANCES" "$UPDATE_STATUS_FILE" "$USER_ENTRIES_STATUS_FILE"; do
+            _index=$((_index + 1))
+            [ -n "$_file" ] || continue
+            if [ -f "${_snapshot}/${_index}" ]; then
+                cp -p "${_snapshot}/${_index}" "$_file" || MakeLogRecord "err" "Preparation rollback failed: ${_file}"
+            else
+                rm -f "$_file"
+            fi
+        done
+    fi
+    rm -rf "$_snapshot"
+    return $_result
+}
+
+PrepareBlacklistFiles() {
     local _return_code=0 _user_entries_ret_code=1
     PreStartCheck
-    AddBypassEntries
+    AddBypassEntries || return 4
     GetMainInstanceEntries
     case $? in
         0)
@@ -1260,7 +1329,7 @@ GetBlacklistFiles() {
     if [ $_return_code -eq 0 ]; then
         _return_code=$_user_entries_ret_code
     fi
-    MergeDnsmasqNftsets || _return_code=1
+    MergeDnsmasqNftsets || return 4
     return $_return_code
 }
 
@@ -1311,6 +1380,11 @@ Update() {
         fi
         GetBlacklistFiles
         _return_code=$?
+        if [ $_return_code -eq 4 ]; then
+            ToggleUPIDFile del
+            MakeToken
+            return 4
+        fi
         UpdateBllistSets
         _upd_sets_ret_code=$?
         # IP data files replace their sets in an nft transaction. Clear only
@@ -1322,7 +1396,10 @@ Update() {
         if [ $_return_code -eq 0 ]; then
             _return_code=$_upd_sets_ret_code
         fi
-        RestartDnsmasq
+        if ! RestartDnsmasq; then
+            MakeLogRecord "err" "dnsmasq restart failed"
+            _return_code=1
+        fi
         ToggleUPIDFile del
         ### Post-update script
         [ -x "$POST_UPDATE_SCRIPT" ] && $POST_UPDATE_SCRIPT &
@@ -1349,21 +1426,31 @@ Start() {
         echo " ${NAME} ${_arg}..."
         MakeLogRecord "info" "${_arg}..."
         DropNetConfig &> /dev/null
-        SetNetConfig
+        SetNetConfig || { DropNetConfig; rm -f "$START_PID_FILE"; return 1; }
         PreStartCheck
-        AddBypassEntries
+        AddBypassEntries || { DropNetConfig; rm -f "$START_PID_FILE"; return 1; }
         # Rebuild local user-entry files so disabled/removed instances cannot
         # leave stale dnsmasq directives or nft data behind after a restart.
-        AddUserEntries cached
+        AddUserEntries cached || { DropNetConfig; rm -f "$START_PID_FILE"; return 1; }
         MergeDnsmasqNftsets
         if [ $? -ne 0 ]; then
+            DropNetConfig
             rm -f "$START_PID_FILE"
             MakeToken
             return 1
         fi
         UpdateBllistSets
         _return_code=$?
-        RestartDnsmasq
+        if ! RestartDnsmasq; then
+            MakeLogRecord "err" "dnsmasq restart failed"
+            _return_code=1
+        fi
+        if [ $_return_code -ne 0 ]; then
+            DropNetConfig
+            rm -f "$START_PID_FILE"
+            MakeToken
+            return $_return_code
+        fi
         if [ "$VPN_ROUTE_CHECK" = "1" -a -x "$ROUTE_CHECK_EXEC" ] && [ "$PROXY_MODE" = "2" -o -n "$USER_INSTANCES_VPN" ]; then
             $ROUTE_CHECK_EXEC start &> /dev/null &
         fi
